Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=
Global $frmMain = GUICreate($botName & " " & $botVersion, 286, 300, 392, 427, -1, $WS_EX_WINDOWEDGE)
GUISetOnEvent($GUI_EVENT_CLOSE, "frmMainClose")

Global $textOutput = GUICtrlCreateEdit("", 0, 185, 284, 113, BitOR($ES_WANTRETURN, $WS_VSCROLL, $ES_AUTOVSCROLL))
_GUICtrlEdit_SetLimitText($textOutput, 100000000)
GUICtrlSetData(-1, "• Thanks for using MSL-Bot!" & @CRLF & "• This is an open-source project so you are allowed to modify and create codes that fit your needs." & @CRLF & "• If you find any bugs/issues or want to say Hi join our Discord, link in the 'About' page." & @CRLF & "• If you find this bot useful, considering supporting me by donating! Link in the 'About' tab." & @CRLF)

Global $Tab1 = GUICtrlCreateTab(0, 0, 284, 161)
GUICtrlSetState(-1, $GUI_FOCUS)

GUICtrlCreateTabItem("Scripts")
Global $cmbLoad = GUICtrlCreateCombo( "Select a script..", 4, 28, 150, 25 )
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "cmbLoadClick")
Global $listScript = GUICtrlCreateList("", 4, 53, 276, 104, BitOR($WS_BORDER, $WS_VSCROLL))
GUICtrlSetData(-1, "")
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $btnEdit = GUICtrlCreateButton("Edit", 228, 28, 43, 25)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "btnEditClick")


Global $TabSheet2 = GUICtrlCreateTabItem("Config")
GUICtrlCreateGroup("", 4, 21, 274, 134)
GUICtrlSetFont(-1, 10, 400, 0, "Arial")
Global $textConfig = GUICtrlCreateInput("config.ini", 12, 36, 80, 22)
GUICtrlSetFont(-1, 10, 400, 0, "Arial")
Global $btnSetConfig = GUICtrlCreateButton("Set", 96, 34, 43, 25)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "btnSetConfig")
Global $listConfig = GUICtrlCreateList("", 9, 60, 263, 96, BitOR($WS_BORDER, $WS_VSCROLL))
GUICtrlSetData(-1, "")
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $btnConfigEdit = GUICtrlCreateButton("Edit", 228, 34, 43, 25)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "btnConfigEdit")
GUICtrlCreateGroup("", -99, -99, 1, 1)


GUICtrlCreateTabItem("Debug")
GUICtrlCreateLabel("Debugging tools:", 8, 29, 100, 17)
GUICtrlSetFont(-1, 10, 400, 0, "Arial")
Global $chkDebugLocation = GUICtrlCreateCheckbox("Location: not started", 88, 49, 200, 17)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "chkDebugLocationClick")
Global $btnSet = GUICtrlCreateButton("Set Location", 12, 48, 70, 20)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "btnSetClick")
Global $chkDebugFindImage = GUICtrlCreateCheckbox("Find Image:", 12, 73, 73, 17)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetOnEvent(-1, "chkDebugFindImageClick")
Global $lblDebugImage = GUICtrlCreateLabel("Found: 0" & @CRLF & "Size: 0", 180, 68, 100, 34)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $textDebugImage = GUICtrlCreateInput("", 88, 71, 90, 22)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $btnDebugTestCode = GUICtrlCreateButton("Test Code:", 11, 97, 59, 25)
GUICtrlSetOnEvent(-1, "btnDebugTestCodeClick")
Global $textDebugTestCode = GUICtrlCreateInput("", 76, 99, 201, 22)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $btnSaveImage = GUICtrlCreateButton("Save As Image: ", 11, 127, 100, 25)
GUICtrlSetOnEvent(-1, "btnSaveImage")
Global $lblDebugCoordinations = GUICtrlCreateLabel("F6: (?, ?) | F7: (?, ?)", 120, 131, 265, 17)
GUICtrlSetFont(-1, 9, 400, 0, "Arial")


GUICtrlCreateTabItem("About")
GUICtrlCreateLabel("This is an open-sourced Monster Super League bot programmed to gain experience and because of the enjoyment of coding.", 8, 29, 250, 38, 0x01)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $lblAuthor = GUICtrlCreateLabel("Author: GkevinOD (gkevinod@gmail.com)", 12, 77, 250, 17)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $lblVersion = GUICtrlCreateLabel("Current version: ", 12, 90, 250, 17)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
Global $lblDiscord = GUICtrlCreateLabel("Discord: https://discord.gg/UQGRnwf", 12, 103, 250, 17)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetCursor(-1, 0)
GuiCtrlSetOnEvent(-1, "lblDiscordClick")
Global $lblDonate = GUICtrlCreateLabel("Donate: https://www.paypal.me/gkevinod", 12, 129, 250, 17)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
GUICtrlSetCursor(-1, 0)
GuiCtrlSetOnEvent(-1, "lblDonateClick")


GUICtrlCreateTabItem("")
Global $btnRun = GUICtrlCreateButton("Start", 8, 160, 75, 25)
GUICtrlSetOnEvent(-1, "btnRunClick")
Global $btnClear = GUICtrlCreateButton("Clear", 200, 160, 75, 25)
GUICtrlSetOnEvent(-1, "btnClearClick")
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###